config/routes.rb
Rails.application.routes.draw do
  resources :movies
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :recipes do
    resources :steps
    member do
      post 'favorite'
      delete 'favorite', action: "unfavorite"
    end
  end

  resources :users

  root to: "recipes#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field :name, type: String
  field :description, type: String
  field :photo, type: String
  field :preptime, type: String
  field :cooktime, type: String
  field :servings, type: String
  field :difficulty, type: String
  field :cuisines, type: Set

  slug :name, history: true

  embeds_many :steps
  has_and_belongs_to_many :favorited_by, class_name: 'User', inverse_of: :favorite_recipes

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])



  end

  def favorite
    @recipe = Recipe.find(params[:id])
    if user_signed_in?
    # @recipe.favorited_by = [current_user]
    @recipe.push(favorited_by_ids: current_user.id)
    current_user.push(favorite_recipe_ids: @recipe.id)
    redirect_to recipe_path(@recipe), notice:"You just add this recipe to your favorites"
    else
      redirect_to recipe_path(@recipe), notice:"If you want to add this recipe to your favorite recipies you need to be #{view_context.link_to "logged in", new_user_session_path}"
    end
  end

  def unfavorite
    @recipe = Recipe.find(params[:id])
    # @recipe.favorited_by = []
    @recipe.pull(favorited_by_ids: current_user.id)
    current_user.pull(favorite_recipe_ids: @recipe.id)
    redirect_to recipe_path(@recipe), notice: @recipe.name + " was remove from your favorites."

  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
      <% @recipes.each do |recipe|%>
      <div class="col s12 m6 l4">
        <div class="card">
          <div class="card-image">
            <img src="https://argentina-travel-blog.sayhueque.com/wp-content/uploads/2015/09/papa.jpg">
            <%= link_to recipe, class: "btn-floating halfway-fab waves-effect waves-light black" do %>
            <i class="material-icons">arrow_forward</i>
            <% end %>
          </div>
          <div class="card-content">
          <span class="recipeTitle"><%= recipe.name %></span>
          <p class="recipeResume"><%= recipe.description %></p>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">

  <!---Recipes Name--->
  <div>
  <h4 class="recipeTitle"><%= @recipe.name %></h4>
  <%# <div class="divider"></div> %>
  </div>

  <!---Recipes Author--->
  <!--TODO -->
  <%# <div class="row authorInfo">
    <div class="col 2"><img class="authorImage circle responsive-img" src="https://cdn-images-1.medium.com/fit/c/200/200/1*fmti2-FyGmZK-DGAHfMlkg.jpeg"></div>
    <div class="author col 2"><p>by Carito</p></div>
  </div> %>
  <%# <h6 class="author"><img class="authorImage circle responsive-img" src="https://cdn-images-1.medium.com/fit/c/200/200/1*fmti2-FyGmZK-DGAHfMlkg.jpeg">By Carito</h4> %>

  <!---Recipes Description--->
  <h6 class="recipeDescription"><%= @recipe.description %></h6>
  <div class="divider"></div>

  <div class="recipeDetails row">
    <div class="col s6 m4 l2"><p><%= "Prep Time: " + @recipe.preptime %></p></div>
    <div class="col s6 m4 l2"><p><%= "Cook Time: " + @recipe.cooktime %></p></div>
    <div class="col s6 m4 l2"><p><%= "Cook Time: " + @recipe.cooktime %></p></div>
    <div class="col s6 m4 l2"><p><%= "Difficulty: " + "Easy" %></p></div>
    <div class="col s6 m4 l2"><p><%= "Cuisine: " + @recipe.cuisines.to_a.to_sentence %></p></div>
    <div class="col s6 m4 l2"><p><%= "Servings: " + @recipe.servings %></p></div>
  </div>

  <!---Recipes Photo--->
  <div class="carousel carousel-slider">
    <a class="carousel-item" href="#one!"><img src="https://lorempixel.com/800/400/food/1"></a>
    <a class="carousel-item" href="#two!"><img src="https://lorempixel.com/800/400/food/2"></a>
    <a class="carousel-item" href="#three!"><img src="https://lorempixel.com/800/400/food/3"></a>
    <a class="carousel-item" href="#four!"><img src="https://lorempixel.com/800/400/food/4"></a>
  </div>

  <!---Recipes Ingredientes--->
  <h5 class="ingredientsTitle">Ingredients</h5>
  <%# <div class="divider"></div> %>
  <div class="ingredientsList">
    <table>
        <tbody>
          <% @recipe.steps.each do |step|%>
            <% step.ingredients.each do |ingredient|%>
              <tr>
                <td><%=ingredient["quantity"][0].to_s + " " +  ingredient["quantity"][1].to_s+ " of " + ingredient["id"] %></td>
              </tr>
            <% end unless step.ingredients.nil? %>
           <% end %>
        </tbody>
      </table>
  </div>

  <!---Buttons--->
  <div class="right-align">
    <div class="row right-align">

     <!---Share--->
    <!-- Modal Trigger -->
      <a class="recipeActions col s12 m3 l3 waves-effect waves-light btn grey darken-4 rigth-align recipe-btn modal-trigger" href="#modal1"><i class="material-icons left">share</i>Share</a>

    <!---Make it--->
      <%= link_to recipe_step_path(@recipe, 1), class: "recipeActions col s12 m3 l3 waves-effect waves-light btn grey darken-4 rigth-align" do %>
      <i class="material-icons left">local_dining</i>Make it
      <% end %>

    <!---Add to favorites--->
      <% if user_signed_in? && current_user.has_favorited?(@recipe)  %>
        <%= link_to favorite_recipe_path(@recipe), method: :delete, class: "recipeActions col s12 m3 l3 waves-effect waves-light btn grey darken-4 rigth-align" do %>
          <i class="material-icons left">favorite</i>Remove from favorites
         <% end %>
      <% else %>
        <%= link_to favorite_recipe_path(@recipe), method: :post, class: "recipeActions col s12 m3 l3 waves-effect waves-light btn grey darken-4 rigth-align" do %>
          <i class="material-icons left">favorite</i>Add to favorites
        <% end %>
      <% end %>
    </div>

    <!-- Modal Structure -->
    <div id="modal1" class="modal">
      <div class="modal-content left-align">
        <h4>Share Recipe</h4>
          <div class="row">
              <div class="col 8"><p>URL: <%= recipe_url %> </p></div>
              <div class="col 4"><a data-copy="<%= recipe_url %>" class="action-copy waves-effect waves-light btn grey darken-4 rigth-align"><i class="material-icons left">content_copy</i>Copy</a></div>
          </div>

      </div>
      <%# TODO%>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
    </div>


  </div>


</div>