Web/Pages/ViewComponents/RecipeCountViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InspiredCooking.Data;

namespace InspiredCooking.Pages.ViewComponents
{
    public class RecipeCountViewComponent
        : ViewComponent
    {
        private readonly IRecipeData recipeData;

        public RecipeCountViewComponent(IRecipeData recipeData)
        {
            this.recipeData = recipeData;
        }

        public IViewComponentResult Invoke()
        {
            var count = recipeData.GetCountOfRecipes();
            return View(count);
        }
    }

    

}

Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - recipes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <base href="~/" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!-- Logo -->
                <a class="navbar-brand" asp-area="" asp-page="/Index"><img src="~/images/logo-green.png" alt="logo" id="logo" /></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Header options  -->
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between header-options">
                    <ul class="navbar-nav flex-grow-1 header-menu">
                        <!-- Home  -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">
                                <p class="nav-item">Home</p>
                            </a>
                        </li>
                        <!-- Recipes  -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page=".\recipes">
                                <p class="nav-item">Recipes</p>
                            </a>
                        </li>
                        <!-- Cookbook  -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page=".\menu">
                                <p class="nav-item">My CookBook</p>
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <!--<p><vc:recipe-count></vc:recipe-count></p>-->
            <p> &copy; 2021 - InspiredCooking </p>

        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>