config/routes.rb
Rails.application.routes.draw do
  resources :movies
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :recipes do
    resources :steps
    member do
      post 'favorite'
      delete 'favorite', action: "unfavorite"
    end
  end

  resources :users

  root to: "recipes#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/step.rb
class Step
  include Mongoid::Document

  field :instructions, type: String
  field :ingredients # No type for now, will create a custom type later.

  embedded_in :recipe
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController


  def show
    @step_number = params[:id].to_i
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps[@step_number-1]
  end


end

app/views/steps/show.html.erb
<div class="container">
    <!---TODO--->
    <h4 class="stepsTitle">Step <%= @step_number.to_s %> of <%= @recipe.steps.count%></h4>
    <div class="divider"></div>

    <% unless @step.ingredients.nil? %>
      <!---Step Ingredients--->
      <div class="row stepIngredients"></div>
      <h5 class="ingredientsTitle">Ingredients</h5>
      <p class="guideText">For this step you'll using the next ingredients:</p>

      <div>
        <table class="ingredientsTable">
            <tbody>
              <% @step.ingredients.each do |ingredient|%>
              <tr>
                <td><%=ingredient["quantity"][0].to_s + " " +  ingredient["quantity"][1].to_s+ " of " + ingredient["id"] %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    <% end %>


    <!---Step Instructions--->
    <div class="row stepInstructions">
      <h5 class="InstructionsTitle">Instructions</h5>
      <p class="typeBody2"><%= @step.instructions %></p>
      <!---Step Photo--->
      <img class="materialboxed stepImage responsive-img" width="650" src="https://argentina-travel-blog.sayhueque.com/wp-content/uploads/2015/09/papa.jpg">
    </div>

<!---Buttons--->
  <div class="right-align">
    <% if @step_number < @recipe.steps.count%>
    <button class="stepActions waves-effect waves-light btn grey darken-4">
        <%= link_to recipe_step_path(@recipe, @step_number +1 ) do %>
        <i class="material-icons left">check</i>Done
        <% end %>
    </button>
    <% end %>
    <p class="guideText">And show me next step!</p>

    <% if @step_number > 1%>
    <button class="stepActions waves-effect waves-light btn grey darken-4">
        <%= link_to recipe_step_path(@recipe, @step_number -1 ) do %>
        <i class="material-icons left">arrow_back</i>Previous Step
        <% end %>
    </button>
    <% end %>

    <% if @step_number == 1%>
    <button class="stepActions waves-effect waves-light btn grey darken-4">
        <%= link_to recipe_path(@recipe) do %>
        <i class="material-icons left">arrow_back</i>Back to recipe
        <% end %>
    </button>
    <% end %>
  </div>
</div>